 const charactersData = [
      {
        "id": 1,
        "name": "Sung Jin-woo",
        "age": 24,
        "gender": "Male",
        "occupation": ["Hunter", "Guild Master"],
        "rank": "E",
        "class": "Mage",
        "guild": ["Ahjin Guild (Guildmaster)"],
        "description": "Sung Jin-Woo is the main protagonist of Solo Leveling. Originally an infamously weak E-Rank Hunter, he got the chance of a lifetime when he was selected as the Player of the System, giving him the unique ability to grow in strength without restraint. Jin-Woo is a confident individual with a strong sense of family and a thirst for power. As a result, he is very close to his mom and sister and rarely wastes an opportunity to grow stronger. Despite being strong and respected, Jin-Woo isn't arrogant and is both polite and easygoing in person. He is also mostly indifferent to materialistic desires such as fame and fortune and can be very selfless. In battle, however, he is ruthless, slaughtering his enemies indiscriminately and even somewhat disdainful.",
        "description_spoiler": null,
        "episodes": [1, 2, 3, 4, 5, 6, 7, 7.5, 8, 9, 10, 11, 12],
        "cover_image_url": require("@/assets/images/characters/Sung Jinwoo.jpg")
      },
      {
        "id": 2,
        "name": "Baek Yoonho",
        "age": "Unknown",
        "gender": "Male",
        "occupation": ["Hunter", "Guild Master"],
        "rank": "S",
        "class": "Fighter",
        "guild": ["Reapers Guild (formerly)", "White Tiger Guild (Guild Master)"],
        "description": "Baek Yoon-Ho is a Korean S-Rank hunter who specializes in transformation magic and the Guild Master of the White Tiger Guild.",
        "description_spoiler": null,
        "episodes": [1, 5, 7.5, 8],
        "cover_image_url": require("@/assets/images/characters/Baek Yoonho.jpg")
      },
      {
        "id": 3,
        "name": "Cha Hae-In",
        "age": 23,
        "gender": "Female",
        "occupation": ["Hunter", "Vice Guild Master"],
        "rank": "S",
        "class": "Sword Fighter",
        "guild": ["Hunters Guild (Vice Guild Master)"],
        "description": "Cha Hae-In is the Vice-Guild Master of the Hunters Guild and the sword woman of the main raiding party. She is the 9th ranked Hunter in South Korea; also being its only female S-Rank Hunter.",
        "description_spoiler": null,
        "episodes": [1, 7, 8, 12],
        "cover_image_url": require("@/assets/images/characters/Cha Hae-In.jpg")
      },
      {
        "id": 4,
        "name": "Choi Jong-In",
        "age": "Unknown",
        "gender": "Male",
        "occupation": ["Hunter", "Guild Master"],
        "rank": "S",
        "class": "Mage",
        "guild": ["Hunters Guild (Guild Master)"],
        "description": "Choi Jong-In is a Korean S-Rank Hunter who specializes in fire magic and the Guild Master of the Hunters Guild. He is displayed as a confident individual that does not falter under pressure even when fighting against powerful magic beasts. Choi Jong-In is also a chain smoker and often found with a cigarette or outside (since some buildings do not allow smoking on the premises). His cigarettes can also be ignited to unleash his fire magic.",
        "description_spoiler": null,
        "episodes": [1, 2, 3, 4, 5, 6],
        "cover_image_url": require("@/assets/images/characters/Choi Jong-In.jpg")

      },
      {
        "id": 5,
        "name": "Eun-Seok",
        "age": "Unknown",
        "gender": "Male",
        "occupation": ["Hunter"],
        "rank": "S",
        "class": "Mage",
        "guild": ["None"],
        "description": "Eunseok is a young and dashing man with brown hair tied into a small bun and had teal eyes. During the Jeju Island Raid, Eunseok wore a dark blue attire with a blue cloak and had a pair of metal claws atop his gauntlets.",
        "description_spoiler": null,
        "episodes": [1],
        "cover_image_url": require("@/assets/images/characters/Eunseok.jpg")

      },
      {
        "id": 6,
        "name": "Go Gunhee",
        "age": 80,
        "gender": "Male",
        "occupation": ["Hunter", "Chairman"],
        "rank": "S",
        "class": "Unidentified",
        "guild": ["Korean Hunter Association"],
        "description": "Go Gun-Hee is the Korean S-Rank Hunter and the Chairman of the Korean Hunters Association. Gun-Hee is a man with an humble, open, and honest personality. He is very appreciative toward those with good morals, but also very distasteful toward those who only aimed for personal gain. As a result of this attitude, Gun-Hee has had a good relationship with Jin-Woo from the moment they met.",
        "description_spoiler": null,
        "episodes": [1, 2, 7, 8],
        "cover_image_url": require("@/assets/images/characters/Go Gunhee.jpg")

      },
      {
        "id": 7,
        "name": "Han Song-Yi",
        "age": "Unknown",
        "gender": "Female",
        "occupation": ["Hunter"],
        "rank": "E",
        "class": "None",
        "guild": ["None"],
        "description": "Han Song-Yi is an E-Rank hunter who quit school after gaining money through the Yoo Jin-Ho and Sung Jin-Woo motley group of party. She is a close friend of Sung Jin-Ah and first appeared when Jin-Ah visited Jin-Woo in the hospital.",
        "description_spoiler": null,
        "episodes": [2, 10],
        "cover_image_url": require("@/assets/images/characters/Han, Song-Yi.jpg")

      },
      {
        "id": 8,
        "name": "Hwang Dongsoo",
        "age": "Unknown",
        "gender": "Male",
        "occupation": ["Hunter"],
        "rank": "S",
        "class": "Fighter",
        "guild": ["Scavenger Guild"],
        "description": "Hwang Dong-Su is a Korean S-Rank Hunter based in America and the younger brother of Hwang Dong-Suk. Hwang is a selfish and sadistic sociopath with little respect for human life. He cared little as to what people thought of him, given his indifference to the fact that he is considered a traitor back home and arrogant to the point of stupidity.",
        "description_spoiler": null,
        "episodes": [7],
        "cover_image_url": require("@/assets/images/characters/Hwang Dongsoo.jpg")

      },
      {
        "id": 9,
        "name": "Hwang Dongsuk",
        "age": "Unknown",
        "gender": "Male",
        "occupation": ["Hunter"],
        "rank": "C",
        "class": "Tanker",
        "guild": ["None"],
        "description": "Hwang Dong-Suk was a hunter whom Jin-Woo accompanied on a raid, as well as the older brother of Hwang Dong-Soo.",
        "description_spoiler": null,
        "episodes": [3, 6, 8],
        "cover_image_url": require("@/assets/images/characters/Hwang Dongsuk.jpg")

      },
      {
        "id": 10,
        "name": "Kang Taeshik",
        "age": "Unknown",
        "gender": "Male",
        "occupation": ["Inspector, Hitman"],
        "rank": "B",
        "class": "Assassin",
        "guild": ["None"],
        "description": "Taeshik was a lanky looking man that appeared to be in his mid to late 20s. He has spiky purple hair with matching purple eyes with a sadistic look to them. As an employee of the Korean Hunters Association, he wore a formal business attire that consists of a black suit and tie with a belt where he held his daggers and knives.",
        "description_spoiler": null,
        "episodes": [2, 3, 6],
        "cover_image_url": require("@/assets/images/characters/Kang Taeshik.jpg")

      },
      {
        "id": 11,
        "name": "Kim Sangshik",
        "age": "Unknown",
        "gender": "Male",
        "occupation": ["Hunter"],
        "rank": "D",
        "class": "Unknown",
        "guild": ["None"],
        "description": "Kim Sangshik is motivated to continue his perilous work as a hunter by his dedication to his family, which includes his wife, their young daughter Eunji who is of kindergarten age, and their eldest daughter Eunha, who is on the verge of starting middle school. Despite the inherent risks of his profession, the well-being and financial security of his family take precedence, driving him to persist as a hunter.",
        "description_spoiler": null,
        "episodes": [1, 3, 5, 8, 9, 12],
        "cover_image_url": require("@/assets/images/characters/Kim Sangshik.jpg")

      },
      {
        "id": 12,
        "name": "Laura",
        "age": "Unknown",
        "gender": "Female",
        "occupation": ["Secretary"],
        "rank": "None",
        "class": "None",
        "guild": ["Scavenger Guild"],
        "description": "Laura is a beautiful young woman with blue eyes and blonde hair that she wears in a bun. She is usually displayed wearing a black business suit. Laura is a composed individual who rarely ever shows emotion. She behaves in a professional manner and is very respectful toward the S-Ranks she works for, notably Thomas Andre and Hwang Dongsoo.",
        "description_spoiler": null,
        "episodes": [7],
        "cover_image_url": require("@/assets/images/characters/Laura.jpg")
      },
      {
        "id": 13,
        "name": "Lee Joo-Hee",
        "age": 22,
        "gender": "Female",
        "occupation": ["Hunter (Formerly)"],
        "rank": "B",
        "class": "Healer",
        "guild": ["None"],
        "description": "Lee Ju-Hee is a former hunter and temporary partner of Jin-Woo in his E-Rank days. She is frequently seen healing Jin-Woo and saved his life many times. Ju-Hee is very kind, especially to Jin-Woo. She healed him every time he got injured and once even thought of Jin-Woo annoying because of injuries kept on appearing on his body, thinking he was stupid sometimes. She was a B-rank hunter but because of fear, she has never attended dungeons higher than C-rank.",
        "description_spoiler": null,
        "episodes": [1, 5, 7.5, 8],
        "cover_image_url": require("@/assets/images/characters/Lee Joohee.jpg")
      },
      {
        "id": 14,
        "name": "Park Beom-Shik",
        "age": "Unknown",
        "gender": "Male",
        "occupation": ["Hunter", "Construction Worker"],
        "rank": "D",
        "class": "Fighter",
        "guild": ["None"],
        "description": "Park Beom-Shik was a Korean D-Rank Hunter and a good friend of Kim Sangshik. Park was a chubby middle-aged man man with curly black hair. During the Double Dungeon Incident, he wore a green sweater over a black shirt, track pants, and sneakers.",
        "description_spoiler": null,
        "episodes": [1, 8, 9, 12],
        "cover_image_url": require("@/assets/images/characters/Park Beom-Shik.jpg")
      },
      {
        "id": 15,
        "name": "Park Kyung-Hye",
        "age": "Unknown",
        "gender": "Female",
        "occupation": "Unknown",
        "rank": "None",
        "class": "None",
        "guild": ["None"],
        "description": "Park Kyung-Hye is Jin-Woo's mother. Kyung-Hye is a very selfless and loving woman who cares about her children more than anything else, as shown when she asked Jin-Woo as to how Jinah was doing almost immediately after waking up from her four-year coma. When Il-Hwan went missing on a raid ten years prior to the start of the story, Kyung-Hye refused to believe that he was dead and took to raising their children by herself. Around four years before the start of the story, Kyung-Hye began to show symptoms of an mana-induced sleeping disorder known as Eternal Slumber. As there was no cure, and it was only a matter of time before she wouldn't be able to stay conscious anymore, she made Jin-Woo promise to take care of Jinah when the disease's full effects set in. When the inevitable moment arrived and she fell into a coma, Jin-Woo decided to follow in his father's footsteps and pursue a career in hunting in order to support both himself and his sister, as well as pay for his mother's hospital bills.",
        "description_spoiler": null,
        "episodes": [1],
        "cover_image_url": require("@/assets/images/characters/Park Kyung-Hye.jpg")
      },
      {
        "id": 16,
        "name": "Song Chi-Yul",
        "age": 57,
        "gender": "Male",
        "occupation": ["Hunter"],
        "rank": "C",
        "class": "Mage",
        "guild": ["None"],
        "description": "Song Chi-Yul is a Korean C-Rank Hunter and a kumdo teacher. He is also one of Jinwoo's old friends, having known him since he was a E-Rank Hunter, and one of the six survivors of the first Double Dungeon incident.",
        "description_spoiler": null,
        "episodes": [1, 3, 4, 5, 6, 8, 9],
        "cover_image_url": require("@/assets/images/characters/Song, Chi-Yul.jpg")
      },
      {
        "id": 17,
        "name": "Sung Jin-Ah",
        "age": "Unknown",
        "gender": "Female",
        "occupation": ["Student"],
        "rank": "None",
        "class": "None",
        "guild": ["None"],
        "description": "Sung Jin-Ah is Jin-Woo's younger sister. She is a hard-working girl who usually tops her exams and has a close relationship with her brother since they are the only siblings in their family. As she grew with only Jin-Woo next to her with her father got stranded in a gate and her mother ending up in coma due to Eternal Sleep, Jin-Ah was always on the edge whenever Jin-Woo is in the hospital and wanted him to stop being a hunter.",
        "description_spoiler": null,
        "episodes": [1, 2, 3, 4, 5, 6, 7, 7.5, 8, 9, 10, 11, 12],
        "cover_image_url": require("@/assets/images/characters/Sung Jinah.jpg")
      },
      {
        "id": 18,
        "name": "Woo Jin-Chul",
        "age": "Unknown",
        "gender": "Male",
        "occupation": ["Hunter", "Chief Inspector"],
        "rank": "A",
        "class": "Fighter",
        "guild": ["None"],
        "description": "Woo Jinchul is a Korean A-Rank Hunter and the current Chairman of the Korean Hunters Association. Before ascending to this role, he was the Chief Inspector of the Hunters Association's Surveillance Team, under the leadership of the previous Chairman, Go Gunhee.",
        "description_spoiler": null,
        "episodes": [1, 3, 5, 6, 8, 9, 12],
        "cover_image_url": require("@/assets/images/characters/Woo Jinchul.jpg")
      },
      {
        "id": 18,
        "name": "Yoo Jin-Ho",
        "age": 22,
        "gender": "Male",
        "occupation": ["Hunter"],
        "rank": "D",
        "class": "Tanker",
        "guild": ["Ahjin Guild (Vice Guild Master)"],
        "description": "Yoo Jin-Ho is Jin-Woo's best friend. Jin-Ho is fiercely loyal toward Jin-Woo and seems to have a desire to make his own living, which likely stems from his high-society background. A running gag to his character is his odd habit of dressing up in very flamboyant and expensive armor whenever he goes on raids.",
        "description_spoiler": null,
        "episodes": [5, 6, 7, 7.5, 8, 10],
        "cover_image_url": require("@/assets/images/characters/Yoo Jinho.jpg")
      }
    ]
    export default charactersData
  