const episodes = [
      {
        "id": 1,
        "episode_number": 1,
        "season_number": 1,
        "title": "I’m Used to It",
        "directed_by": "Shunsuke Nakashige",
        "written_by": "Noboru Kimura",
        "screenplay_by": "Shunsuke Nakashige, Hirotaka Tokuda",
        "original_air_date": "2024-01-07",
        "summary": "Sung Jin-woo, considered the weakest Hunter in the world, enters a dungeon gate with his friend Lee Joo-hee and other stronger Hunters. After the boss is killed, the gate does not collapse but instead reveals a second connected dungeon. The party is split evenly on whether or not to proceed; Jin-woo casts the tiebreaker to send them down into the second half of the double dungeon. The party finds the dungeon empty save for a large room filled with statues, which come alive and begin slaughtering the Hunters.",
        "characters": [
          "Sung Jin-woo",
          "Baek Yoonho",
          "Cha Hae-In",
          "Choi Jong-In",
          "Eun-Seok",
          "Go Gunhee",
          "Kim Sangshik",
          "Lee Joo-Hee",
          "Park Beom-Shik",
          "Song Chi-Yul",
          "Sung Jin-Ah",
          "Woo Jin-Chul"
        ],
        "cover_image_url":require("@/assets/images/episodes/1.jpg")
      },
      {
        "id": 2,
        "episode_number": 2,
        "season_number": 1,
        "title": "If I Had One More Chance",
        "directed_by": "Yūya Horiuchi",
        "written_by": "Fūka Ishii",
        "screenplay_by": "Yūya Horiuchi",
        "original_air_date": "2024-01-14",
        "summary": "Jin-woo realizes that the dungeon they are in has specific rules by which to survive the statues - first, to 'revere God,' second to 'praise God,' and finally to 'prove your faith to God.' Several Hunters are killed as Jin-woo and the senior Hunter leading the party, Song Chi-yul, slowly manage to decipher the instructions on how to survive. Finally, only Chi-yul, Joo-hee (who has collapsed from the stress), and Jin-woo are left, and Jin-woo tells Chi-yul to evacuate with Joo-hee while he holds the door. Left alone, Jin-woo rages against his imminent death. However, as he dies, he receives a message that he has completed the hidden quest and may become a [Player] if he accepts the offer.",
        "characters": [
          "Sung Jin-woo",
          "Choi Jong-In",
          "Go Gunhee",
          "Han Song-Yi",
          "Kang Taeshik",
          "Sung Jin-Ah"
        ],
        "cover_image_url": require("@/assets/images/episodes/2.jpg")
      },
      {
        "id": 3,
        "episode_number": 3,
        "season_number": 1,
        "title": "It’s Like a Game",
        "directed_by": "Takayuki Kikuchi",
        "written_by": "Shingo Irie",
        "screenplay_by": "Takayuki Kikuchi",
        "original_air_date": "2024-01-21",
        "summary": "Jin-woo wakes up after three days asleep, initially thinking he might have dreamed the events of the double-dungeon. Investigators from the Hunters Association explain that it really did happen - Joo-hee is traumatized while Chi-yul is reportedly retiring after losing his arm - and check to see if Jin-woo experienced the very rare 'second awakening', in which a Hunter will experience an increase in ability. The test comes back negative. Jin-woo discovers a message like the one that declared him a player with daily goals to hit and a penalty for failing to complete them. After skipping the first day and nearly dying when thrown into a penalty quest, Jin-woo begins completing each day's goal. He receives stat bonuses and loot boxes, which results in him receiving a special item - an instance dungeon key. He enters and is confronted by a wolf monster stronger than anything he had fought before.",
        "characters": [
          "Sung Jin-woo",
          "Choi Jong-In",
          "Hwang Dongsuk",
          "Kang Taeshik",
          "Kim Sangshik",
          "Lee Joo-Hee",
          "Song Chi-Yul",
          "Sung Jin-Ah",
          "Woo Jin-Chul"
        ],
        "cover_image_url": require("@/assets/images/episodes/3.jpg")
      },
      {
        "id": 4,
        "episode_number": 4,
        "season_number": 1,
        "title": "I’ve Gotta Get Stronger",
        "directed_by": "Tōru Hamasaki",
        "written_by": "Shingo Irie",
        "screenplay_by": "Ikuo Morimoto, Yoshihiro Kanno",
        "original_air_date": "2024-01-28",
        "summary": "Jin-woo successfully kills the wolf and gains a level. More appear, and he continues through the dungeon, killing more and more and gaining more strength before defeating the dungeon's boss. Meanwhile, outside the instance, a dungeon break (a dungeon is not cleared properly and monsters escape into the real world) occurs, allowing a golem to enter the real world. Arriving Hunters, including a PTSD-stricken Joo-hee, fail to deal any damage. Emerging from the instance, Jin-woo is guided to the battle and throws his broken sword into the golem boss, shattering its defense and allowing the gathered Hunters to take it down. He departs, reflecting that the golem must have been more injured than he'd expected.",
        "characters": [
          "Sung Jin-woo",
          "Choi Jong-In",
          "Song Chi-Yul",
          "Sung Jin-Ah"
        ],
        "cover_image_url": require("@/assets/images/episodes/4.jpg")
      },
      {
        "id": 5,
        "episode_number": 5,
        "season_number": 1,
        "title": "A Pretty Good Deal",
        "directed_by": "Makiko Hayase",
        "written_by": "Norimitsu Kaihō",
        "screenplay_by": "Makiko Hayase",
        "original_air_date": "2024-02-04",
        "summary": "Jin-woo joins C-rank Hunter Hwang Dongsuk and his five associates in a pick-up group to tackle a C-rank insect dungeon, with the contract stipulating that Jin-woo doesn't have to fight but won't get any battle drops; Jin-woo becomes suspicious of Dongsuk's motives due to the situation. Rounding out the eight-member requirement to enter the dungeon is first-timer D-rank Yoo Jin-ho, whose family wealth has gotten him equipped with very expensive and powerful gear. After the Hunters defeat a wave of monster ants, they find the dungeon boss - a giant sleeping spider in a room with highly valuable mineable mana crystals. Jin-ho reviews Jin-woo's contract and notes that since the crystals aren't battle drops, Jin-woo should get a full share. In retaliation, Dongsuk and his party spring their plan to keep everything and trap Jin-woo and Jin-ho in the boss room, waking up the spider in the process. Jin-woo prepares to kill the dungeon boss.",
        "characters": [
          "Sung Jin-woo",
          "Baek Yoonho",
          "Choi Jong-In",
          "Lee Joo-Hee",
          "Kim Sangshik",
          "Song Chi-Yul",
          "Sung Jin-Ah"
        ],
        "cover_image_url": require("@/assets/images/episodes/5.jpg")
      },
      {
        "id": 6,
        "episode_number": 6,
        "season_number": 1,
        "title": "The Real Hunt Begins",
        "directed_by": "Takashi Sakuma",
        "written_by": "Norimitsu Kaihō",
        "screenplay_by": "Takashi Sakuma, Yoshihiro Kanno",
        "original_air_date": "2024-02-11",
        "summary": "Jin-woo successfully defeats the boss, much to Jin-ho's shock. When Dongsuk and his group re-enter the boss room, he attempts to coerce Jin-ho into killing Jin-woo, but Jin-ho refuses. Jin-woo receives a new quest to kill Dongsuk's group under penalty of death, leading him to massacre them. He exits the dungeon with Jin-ho, using the cover story of the others having been slain by the dungeon monsters.",
        "characters": [
          "Sung Jin-woo",
          "Choi Jong-In",
          "Hwang Dongsoo",
          "Kang Taeshik",
          "Lee Joo-Hee",
          "Song Chi-Yul",
          "Sung Jin-Ah",
          "Woo Jin-Chul"
        ],
        "cover_image_url": require("@/assets/images/episodes/6.jpg")
      },
      {
        "id": 7,
        "episode_number": 7,
        "season_number": 1,
        "title": "Let’s See How Far I Can Go",
        "directed_by": "Yūya Horiuchi",
        "written_by": "Shigeru Murakoshi",
        "screenplay_by": "Yūya Horiuchi",
        "original_air_date": "2024-02-18",
        "summary": "Jin-ho offers Jin-woo a building in exchange for his help in fulfilling requirements for guild certification; Jin-woo rejects the offer. Jin-woo notices his daily mission keeps incrementing past the requirements. Upon maxing it out, he is rewarded with another instance key - this time to an S-rank dungeon that rewards a special potion that can heal any illness; Jin-woo realizes it can cure his mother and decides to risk it. The first battle within the dungeon is against a guardian Cerberus, which nearly kills Jin-woo multiple times before he finally manages to slay the beast. His reward is the key to the castle Cerberus was guarding, within which is the ingredients he needs to craft the potion. Knowing he would die if he pressed on, he promises himself to return later and succeed. Meanwhile, the Hunters Association investigates the death of Dongsuk after learning the dungeon boss was defeated. Dongsuk's younger brother, the S-rank Dongsoo, blames Jin-woo and Jin-ho and swears revenge.",
        "characters": [
          "Sung Jin-woo",
          "Baek Yoonho",
          "Cha Hae-In",
          "Go Gunhee",
          "Laura",
          "Lee Joo-Hee",
          "Sung Jin-Ah"
        ],
        "cover_image_url": require("@/assets/images/episodes/7.jpg")
      },
      {
        "id": 8,
        "episode_number": 7.5,
        "season_number": 1,
        "title": "How to Get Stronger",
        "directed_by": "",
        "written_by": "",
        "screenplay_by": "",
        "original_air_date": "2024-02-25",
        "summary": "A recap special covering events from the first seven episodes.",
        "characters": [
          "Sung Jin-woo",
          "Baek Yoonho",
          "Cha Hae-In",
          "Choi Jong-In",
          "Eun-Seok",
          "Go Gunhee",
          "Han Song-Yi",
          "Hwang Dongsoo",
          "Kang Taeshik",
          "Kim Sangshik",
          "Laura",
          "Lee Joo-Hee",
          "Park Beom-Shik",
          "Park Kyung-Hye",
          "Song Chi-Yul",
          "Sung Jin-Ah",
          "Woo Jin-Chul",
          "Yoo Jin-Ho"
        ],
        "cover_image_url": require("@/assets/images/episodes/2.webp")
      },
      {
        "id": 9,
        "episode_number": 8,
        "season_number": 1,
        "title": "This Is Frustrating",
        "directed_by": "Hiromu Ōshiro",
        "written_by": "Shunsuke Nakashige",
        "screenplay_by": "Hiromu Ōshiro",
        "original_air_date": "2024-03-03",
        "summary": "Jin-woo visits his comatose mother and decides to push forward with getting stronger so that he can get the needed ingredients to save her; he thus accepts Jin-ho's request to aid in running dungeons to allow creation of a guild. To fulfill the party member requirement for C-rank dungeons, the Hunters Association recruits the survivors of the double dungeon raid (Jin-woo, Joo-hee, Chi-yul, Kim Sangshik, and Kang Jeongho), and due to a shortage of Hunters in the area, the group is rounded out by several imprisoned Hunters, who serve in exchange for reduced sentences, that are overseen by B-rank Kang Taeshik.",
        "characters": [
          "Sung Jin-woo",
          "Baek Yoonho",
          "Cha Hae-In",
          "Go Gunhee",
          "Hwang Dongsoo",
          "Kim Sangshik",
          "Lee Joo-Hee",
          "Park Beom-Shik",
          "Song Chi-Yul",
          "Sung Jin-Ah",
          "Woo Jin-Chul"
        ],
        "cover_image_url": require("@/assets/images/episodes/8.jpg")
      },
      {
        "id": 10,
        "episode_number": 9,
        "season_number": 1,
        "title": "You’ve Been Hiding Your Skills",
        "directed_by": "Hirotaka Tokuda",
        "written_by": "Shingo Irie",
        "screenplay_by": "Hirotaka Tokuda",
        "original_air_date": "2024-03-10",
        "summary": "At a three-way junction, the group splits up. Kang uses the separation to murder the prisoners at the behest of their victim's father, and when Jeongho and Sangshik's path leads them to stumble upon the scene, Kang kills them to cover it up. Jin-woo, Joo-hee, and Chi-yul race back to the scene and confront Kang, and Jin-woo reveals his newfound power to kill Kang. A grateful Chi-yul covers for Jin-woo. Later that night, Joo-hee asks Jin-woo if he 'remembers', holding up a small Essence Stone.",
        "characters": [
          "Sung Jin-woo",
          "Kim Sangshik",
          "Park Beom-Shik",
          "Song Chi-Yul",
          "Sung Jin-Ah",
          "Woo Jin-Chul"
        ],
        "cover_image_url": require("@/assets/images/episodes/9.jpg")
      },
      {
        "id": 11,
        "episode_number": 10,
        "season_number": 1,
        "title": "What Is This, a Picnic?",
        "directed_by": "Yūya Horiuchi, Takashi Sakuma",
        "written_by": "Yoshikazu Tominaga",
        "screenplay_by": "Kōki Onoue",
        "original_air_date": "2024-03-17",
        "summary": "Joo-hee tells Jin-woo she is retiring as a Hunter, and to look her up if he ever finds himself at her home. Jin-ho buys the dungeon rights for multiple C-rank dungeons and recruits low-ranked Hunters to fill dungeon requirements while Jin-woo and Jin-ho are the only ones who go in to clear them. The White Tiger Guild's recruiting manager notices Sung Jin-woo's name and puts the pieces together that Jin-woo must have reawakened. He attempts to recruit Jin-woo but fails. Jin-woo receives a message - having achieved a level requirement, he is now offered a job-change quest.",
        "characters": ["Sung Jin-woo", "Han Song-Yi", "Sung Jin-Ah"],
        "cover_image_url": require("@/assets/images/episodes/10.jpg")
      },
      {
        "id": 12,
        "episode_number": 11,
        "season_number": 1,
        "title": "A Knight Who Defends an Empty Throne",
        "directed_by": "Takayuki Kikuchi",
        "written_by": "Noboru Kimura",
        "screenplay_by": "Takayuki Kikuchi",
        "original_air_date": "2024-03-24",
        "summary": "Jin-woo starts the job-change quest, and is teleported to a massive castle. After fighting through waves of knights, assassins, and mages (apparently mimicking those he's fought previously) he confronts Igris, the Bloodred Knight Commander. Igris is every bit as powerful and moreso than Jin-woo, who only barely manages to slay the Knight. The actual job-change quest activates, unleashing an unending horde of the monsters he'd fought on the way to Igris' chamber. Meanwhile, the S-rank hunters of Korea gather and head for Jeju Island.",
        "characters": ["Sung Jin-woo", "Sung Jin-Ah"],
        "cover_image_url": require("@/assets/images/episodes/11.jpg")
      },
      {
        "id": 13,
        "episode_number": 12,
        "season_number": 1,
        "title": "Arise",
        "directed_by": "Shunsuke Nakashige",
        "written_by": "Noboru Kimura",
        "screenplay_by": "Shunsuke Nakashige",
        "original_air_date": "2024-03-31",
        "summary": "Overwhelmed by the seemingly endless horde and recalling his prior circumstances, Jin-woo nearly despairs before deciding to press forward. The timer for the daily quest expires and he is transferred to a penalty zone, which he uses to recover and prepare himself. Returned to the castle, he succeeds in defeating first the horde. As a reward he gains the title 'Shadow Monarch' and the ability to bring the dead back to life as his 'shadow army.' Meanwhile, the S-rank hunters make a horrifying discovery - the Jeju Island S-rank monsters have begun to evolve.",
        "characters": [
          "Sung Jin-woo",
          "Cha Hae-In",
          "Kim Sangshik",
          "Park Beom-Shik",
          "Sung Jin-Ah",
          "Woo Jin-Chul"
        ],
        "cover_image_url": require("@/assets/images/episodes/12.jpg")
      }
    ]
  
  export default episodes